services:
  - type: web
    name: building-something-with-express
    env: node
    nodeVersion: 20.11.1
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 